---
scorecard:
  init-timeout: 120
  output: json
  bundle: "deploy/olm-catalog/ibm-spectrum-scale-csi-operator/"
  plugins:
    - basic:
        namespace: "ibm-spectrum-scale-csi-driver"
        cr-manifest:
          - "deploy/crds/csiscaleoperators.csi.ibm.com.cr.yaml"
    - olm:
        namespace: "ibm-spectrum-scale-csi-driver"
        cr-manifest:
          - "deploy/crds/csiscaleoperators.csi.ibm.com.cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-spectrum-scale-csi-operator/1.1.0/ibm-spectrum-scale-csi-operator.v1.1.0.clusterserviceversion.yaml"
        proxy-pull-policy: "Never"
